## ESMA 3016
### Edgar Acuna
### El problema de los cumpleanos y la probabilidad de corridas usando simulacion
#### Febrero del 2019
Uso de las librerias numpy, pandas,math y random

In [3]:
import numpy as np
import pandas as pd
import random as rd
from math import factorial 

In [4]:
#Calculando el factorial de 7
factorial(7)

5040

In [5]:
#Calculando el numero de permutaciones de 8 objetos ordenados de 3 en 3
factorial(8)/factorial(5)

336.0

In [6]:
#Calculando el numero de combinaciones de 8 objetos tomados de 3 en 3
factorial(8)/factorial(3)/factorial(5)

56.0

#### Problema de las cumpleanos. Cual es la probabilidad de que en un grupo de 25 personas por los menos dos de ellas cumplan anos el mismo dia.

Calculando la probabilidad exacta
Haciendolo por complemento La solucion exacta es $1-P(365,25)/365^{25}=.5686$.
$p1=1-factorial(365)/(factorial(340)*365^{25})$ da Overflow

Una mejor alternativa es usando productorios

In [7]:
from numpy import prod
lista=range(0,25)
1-prod([1-(i/365) for i in lista])

0.5686997039694639

In [10]:
#simulando un resultado posibel de los 25 cumpleanos
a=np.random.choice(range(1,366),25)
a

array([288,  41,  37, 212, 320, 164, 236, 290,  22, 160,  34, 327, 227,
        88,  14, 308,  26, 134, 343, 174, 157, 320, 196, 240, 223])

In [11]:
#Hallando los dias que son distintos
np.unique(a)

array([ 14,  22,  26,  34,  37,  41,  88, 134, 157, 160, 164, 174, 196,
       212, 223, 227, 236, 240, 288, 290, 308, 320, 327, 343])

Si arreglo unique(a) tiene longitud 25 entonces todos han cumplido anos en dias distintos

In [22]:
#Estimando la probabilidad haciendo  10000 simulaciones
#a=np.random.choice(range(1,366),25)
#b=25-len(np.unique(a))
#40)print b
# Se usa el caracter _ con for para indicar que el comando antes del for se repite 10000 veces
bdays=[25-len(np.unique(np.random.choice(range(1,366),25))) for _ in range(10000)]
a=np.nonzero(bdays)
p1est=len(np.transpose(a))/10000
p1est

0.5698

#### Problema de las corridas.Cual es la probabilidad de que si estacionan 8 carros al azar en un estacionamiento donde hay 12 espacios, los 4 espacios vacios queden juntos?

la contestacion exacta es fact(9)/P(12,8)=9!x4!/12!=.0181

Consideremos como 1 si el espacio en el estacionamiento es ocupado
y 0 si no es ocupado. Lo que queremos es  una secuencia como
$110000111111$. La secuencia $10001111110$ no se es deseada
Simulando 10000 maneras de estacionarse


In [34]:
#Definiendo una secuencia de tamano 12 que contiene cuatro 0's y ocho 1's
a=[0,0,0,0,1,1,1,1,1,1,1,1]

In [35]:
# Haciendo un reordenamiento de los elementos de a
np.random.shuffle(a)
a

[0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1]

In [36]:
#Haciendo una funcion para encontrar el inicio y el final de las corridas de ceros
def zero_runs(a):
    # Creando un arreglo que es 1 cuando el elemnto de a es 0 y que es 0 en caso contario
    # y que anade un 0 en cada extremo del arregloa is 0.
    iszero = np.concatenate(([0], np.equal(a, 0).view(np.int8), [0]))
    #Hallando las diferencias consecutivas, en valor absoluto
    absdiff = np.abs(np.diff(iszero))
    # Hallando las corridas de ceros estableciendo donde  absdiff es 1.
    ranges = np.where(absdiff == 1)[0].reshape(-1, 2)
    return ranges

In [31]:
runs_a=zero_runs(a)
print(runs_a)

[[ 2  4]
 [ 6  7]
 [ 9 10]]


In [37]:
# haciendo una funcion que encuentre el mayor valor de la corrida en cada repeticion
def max_run(a):
    np.random.shuffle(a)
    runs = zero_runs(a)
    maxrun = np.max(runs[:,1]-runs[:,0])
    return maxrun               

In [38]:
# Estimando la probabilidad mediante el conteo de todos los resultados donde el valor maximo de la corrida es 4
a=[0,0,1,1,1,1,1,1,0,1,0,1]
b1=[max_run(a) for _ in range(100000)]
b1.count(4)/float(100000)

0.01751