## ESMA 3016, Lab 10
### Calculo de Probabilidades usando simulacion
### Edgar Acuna
#### Septiembre del 2019
#### Uso de las librerias numpy, pandas y random

In [1]:
import numpy as np
import pandas as pd
import random as rd

Seleccionando al azar un numero entre 0 y 1

In [2]:
rd.random()

0.004724722724763986

In [9]:
rd.sample(range(100),10)

[64, 38, 20, 89, 69, 88, 51, 72, 76, 90]

Seleccionando al azar y sin reemplazo 1000 muestras de tamano 6 de los digitos el 1 al 6

In [10]:
runs=[rd.sample(range(1,7),6) for _ in range(1000)]
runs

[[3, 1, 4, 5, 2, 6],
 [6, 3, 2, 1, 5, 4],
 [6, 2, 3, 4, 5, 1],
 [1, 2, 5, 4, 3, 6],
 [6, 4, 3, 1, 2, 5],
 [6, 3, 1, 4, 5, 2],
 [4, 6, 1, 2, 3, 5],
 [4, 1, 3, 5, 2, 6],
 [1, 3, 6, 2, 5, 4],
 [1, 4, 3, 6, 5, 2],
 [5, 1, 4, 2, 3, 6],
 [4, 3, 6, 5, 2, 1],
 [2, 1, 4, 5, 6, 3],
 [1, 4, 6, 2, 5, 3],
 [1, 4, 2, 5, 6, 3],
 [2, 1, 3, 6, 5, 4],
 [6, 2, 4, 5, 1, 3],
 [6, 5, 4, 2, 3, 1],
 [6, 4, 2, 1, 3, 5],
 [4, 2, 6, 1, 3, 5],
 [2, 1, 6, 5, 4, 3],
 [6, 3, 4, 2, 5, 1],
 [2, 4, 3, 1, 5, 6],
 [2, 6, 4, 1, 5, 3],
 [5, 4, 6, 1, 2, 3],
 [3, 2, 4, 5, 6, 1],
 [1, 3, 6, 2, 4, 5],
 [6, 1, 2, 3, 5, 4],
 [1, 4, 2, 3, 6, 5],
 [2, 6, 4, 1, 3, 5],
 [5, 1, 2, 3, 6, 4],
 [5, 1, 2, 4, 3, 6],
 [1, 2, 4, 3, 6, 5],
 [1, 2, 3, 6, 4, 5],
 [2, 5, 3, 6, 4, 1],
 [1, 5, 3, 2, 4, 6],
 [6, 1, 5, 2, 4, 3],
 [5, 4, 6, 1, 3, 2],
 [3, 1, 6, 5, 2, 4],
 [4, 2, 1, 5, 6, 3],
 [2, 1, 3, 6, 4, 5],
 [6, 1, 2, 5, 4, 3],
 [1, 6, 4, 5, 3, 2],
 [5, 1, 3, 6, 2, 4],
 [1, 5, 3, 6, 2, 4],
 [4, 6, 1, 3, 5, 2],
 [3, 1, 6, 2, 4, 5],
 [5, 6, 2, 1,

In [3]:
#extrayendo una muestra sin reemplazo de tamano 6 de una poblacion dada
population=[4,5,6,12,17,23,22,11,15]
rd.sample(population,5)

[12, 5, 23, 4, 22]

In [4]:
#extrayendo una muestra con reemplazo de tamano 6 de una poblacion dada
population=[4,5,6,12,17,23,22,11,15]
np.random.choice(population,5)

array([12, 11,  4,  4,  4])

### Ejemplo 1

Juan y Luis toman un ascensor en el estacionamiento de
un edificio que tiene 6 pisos. Si ellos se bajan al azar en alguno
 de los pisos (el del estacionamiento es piso CERO),.

Estimar la probabilidad de que ellos se bajen en pisos distintos. 

La solucion exacta es 30/36=5/6=.8333

In [5]:
#Simulando 100 veces el piso en que se baja Juan
juan=np.random.choice(range(1,7),1000)
juan

array([6, 2, 4, 4, 4, 2, 6, 6, 6, 5, 5, 1, 6, 5, 4, 5, 1, 5, 3, 5, 2, 3,
       6, 4, 5, 2, 2, 4, 6, 5, 1, 3, 1, 4, 5, 3, 6, 3, 3, 5, 1, 5, 6, 4,
       1, 5, 3, 6, 3, 2, 5, 2, 1, 6, 2, 1, 6, 2, 5, 6, 4, 5, 4, 2, 2, 2,
       2, 1, 2, 3, 6, 3, 5, 5, 3, 3, 5, 2, 4, 4, 3, 3, 2, 3, 3, 5, 2, 4,
       5, 3, 5, 3, 2, 6, 4, 1, 3, 6, 3, 1, 1, 2, 5, 3, 6, 1, 4, 2, 4, 2,
       4, 3, 6, 1, 1, 2, 5, 2, 1, 3, 2, 2, 3, 2, 4, 1, 2, 6, 6, 2, 3, 6,
       2, 1, 5, 2, 3, 3, 1, 6, 1, 3, 4, 1, 6, 1, 5, 1, 5, 1, 5, 2, 6, 6,
       2, 2, 4, 5, 5, 3, 1, 2, 4, 5, 6, 4, 5, 1, 5, 2, 5, 4, 3, 5, 5, 1,
       4, 4, 1, 2, 5, 3, 6, 5, 2, 3, 6, 1, 3, 3, 6, 3, 2, 3, 2, 3, 5, 6,
       6, 4, 4, 5, 6, 5, 6, 4, 2, 5, 6, 5, 6, 3, 2, 4, 5, 2, 5, 5, 1, 1,
       3, 2, 2, 4, 1, 5, 5, 2, 2, 4, 3, 6, 5, 5, 2, 3, 6, 5, 4, 4, 3, 3,
       5, 3, 5, 2, 4, 5, 2, 3, 5, 4, 4, 2, 2, 4, 5, 1, 2, 3, 5, 2, 3, 1,
       1, 5, 1, 2, 4, 5, 4, 3, 4, 3, 6, 3, 2, 6, 4, 4, 2, 5, 3, 3, 1, 3,
       1, 5, 4, 1, 3, 2, 2, 4, 4, 1, 6, 2, 4, 3, 3,

In [6]:
#Contando las veces que Juan se bajo en uno de los pisos
np.bincount(juan)

array([  0, 155, 185, 169, 163, 178, 150], dtype=int64)

In [10]:
#Simulando 100 veces el piso en que se baja Luis
luis=np.random.choice(range(1,7),1000)

In [11]:
#Encontrando la cantidad de veces que ellos se bajen en distintos pisos
np.sum(juan!=luis)

836

In [12]:
#Haciendo una funcion que estime la probabilidad del evento basado en k simulaciones
def prob_est1(k):
    juan=np.random.choice(range(1,7),k)
    luis=np.random.choice(range(1,7),k)
    return np.sum(juan!=luis)/k

In [13]:
#Estimando la probabilidad, simulando 1000 experimentos
prob_est1(1000)

0.834

In [14]:
#Estimando la probabilidad, simulando 100000 experimentos
prob_est1(100000)

0.83187

### Ejemplo 2

Se extraen tres bolas con REEMPLAZO de una caja que tiene 10 bolas numeradas del 1 al 10
Cual es la probabilidad de que el mayor de los tres numeros extraidos sea 6.

La contestacion exacta es 91/1000=.091.

In [20]:
#Eligiendo las tres bolas al azar 10000 veces
b1=np.random.choice(range(1,11),1000)
b2=np.random.choice(range(1,11),1000)
b3=np.random.choice(range(1,11),1000)

In [21]:
#Formando un data frame de los resultados
data=[b1,b2,b3]
df=pd.DataFrame(data,index=['b1','b2','b3'])
print(df)
#hallando el maximo de cada columna
m=df.max(axis=0)
print(m)

    0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
b1    8    2    4    8    3    7    6    5    1   10  ...    9    3    7    5   
b2    3    2    7    2    2    3    2    8   10   10  ...    7    4    7    9   
b3    9    1    7    2    6    4    2    3   10    6  ...    3    6    5    9   

    994  995  996  997  998  999  
b1    8    1    2    3   10    8  
b2    9    3   10   10    2    9  
b3    7    4    6    4    3    1  

[3 rows x 1000 columns]
0       9
1       2
2       7
3       8
4       6
       ..
995     4
996    10
997    10
998    10
999     9
Length: 1000, dtype: int64


In [22]:
#Contando cuando de estos maximos son 6
(m==6).sum()

96

In [15]:
#Haciendo una funcion para estimar la probabilidad de que el mayor valor extraido sea
#igual aun valor dado usando k simulaciones
def prob_est2(valor,k):
    """
    :param valor: Es el valor del mayor valor  ebtre los numero elegidos
    :param k: Es el numero de simulaciones a usar.
    """
    import numpy as np
    import pandas as pd
    b1=np.random.choice(range(1,11),k)
    b2=np.random.choice(range(1,11),k)
    b3=np.random.choice(range(1,11),k)
    data=[b1,b2,b3]
    df=pd.DataFrame(data,index=['b1','b2','b3'])
    m=df.max(axis=0)
    return (m==valor).sum()/k

In [16]:
#estimando la probabilidad con 100 simulaciones
prob_est2(6,100)

0.1

In [17]:
#estimando la probabilidad con 1,000 simulaciones
prob_est2(6,1000)

0.083

In [18]:
#estimando la probabilidad con 109,000 simulaciones
prob_est2(6,100000)

0.09055

### Ejemplo 3

Una clase la estan tomando 10 estudiantes: 4 Graduados y 6 subgraduados. Se da el primer examen y resulta que todas las notas son distintas. Cual es la probabilidad de que las 4 mejores notas sean de estudiantes graduados?

La probabilidad exacta es 4!6!/10!=1/210=0.0047619

In [57]:
# Sea 0 que represnta la nota de un estudiante subgraduado y 1 la de un estudiante graduado
#esta es una forma de ordenar los datos
a1=[0,0,0,0,0,0,1,1,1,1]
np.random.shuffle(a1)
a1

[1, 0, 0, 0, 1, 0, 0, 1, 1, 0]

Hay que buscar por todos los casos favorables de la forma [1,1,1,1,0,0,0,0,,0,0]. Esto equivale a que la suma de los 4 primeros elementos del arreglo sea 4.

In [58]:
def sum4(a1):
    np.random.shuffle(a1)
    return np.sum(a1[:4])

In [59]:
b2=[sum4(a1) for _ in range(1000000)]
print("la probabilidad estimada es:",b2.count(4)/1000000)


la probabilidad estimada es: 0.004742


In [96]:
def prob_est3(valor,k):
    a1=[0,0,0,0,0,0,1,1,1,1]
    b=0
    for i in range(k):
        np.random.shuffle(a1)
        if(np.sum(a1[:4])==4):
            b=b+1
    print("prob estimada=",b/k)

In [97]:
prob_est3(4,10000)

prob estimada= 0.0048
